DROP TABLE IF EXISTS candies;
DROP TABLE IF EXISTS podcasts;
DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS trees;

CREATE TABLE candies(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  flavor TEXT NOT NULL
);

CREATE TABLE podcasts(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  host TEXT NOT NULL,
  co_host TEXT,
  url TEXT NOT NULL
);

CREATE TABLE cars (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INTEGER NOT NULL,
  color TEXT NOT NULL
);

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  series TEXT
);

CREATE TABLE trees (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  oregon_native BOOLEAN,
  use TEXT NOT NULL
);