DROP TABLE IF EXISTS candies;
DROP TABLE IF EXISTS podcasts;

CREATE TABLE candies(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  flavor TEXT NOT NULL
);

CREATE TABLE podcasts(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  host TEXT NOT NULL,
  co_host TEXT,
  url TEXT NOT NULL
);

